name: CI Pipeline
on: [push, pull_request]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Added to prevent timeouts/cancels
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: 18 }
      - run: npm install
      - run: npx update-browserslist-db@latest  # Added for deps
      - run: npm run lint -- --fix  # Added for lint
      - run: npm run build
      - run: npm test -- --coverage
      - run: npm run package
      - name: Simulate Deploy
        run: echo "Deployment would happen here (e.g., Docker push)"
      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/